version: "3"

tasks:
  build:
    desc: Build the binary
    cmds:
      - go build -o google-mcp .

  run:
    desc: Run the binary
    cmds:
      - go run .

  test:
    desc: Run unit tests (fast, no credentials needed)
    cmds:
      - go test -race -short ./...

  test:integration:
    desc: Run all tests including integration (requires credentials and accounts)
    cmds:
      - go test -race -timeout 5m ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  install:
    desc: Build and install to ~/.local/bin
    cmds:
      - go build -o ~/.local/bin/google-mcp .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f google-mcp

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy
